name: Coverage Reporter
on: [push]

jobs:
  coverage:
    name: Coverage Report
    runs-on: ubuntu-latest
    env:
      ST_IMAGE: Squeak64-trunk
    steps:
      - uses: actions/checkout@v2
      - uses: hpi-swa/setup-smalltalkCI@v1
        id: smalltalkci
        with:
          smalltalk-image: ${{ env.ST_IMAGE }}
      - run: smalltalkci -s ${{ env.ST_IMAGE }} ./.coverage.smalltalk.ston
        shell: bash
        timeout-minutes: 15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
