name: Release

env:
  smalltalk: 'Squeak64-5.3'
  PATH_TO_SAR: '/home/runner/.smalltalkCI/_builds/Algernon.sar'

on:
  push:
    tags:
      - "v*"
jobs:
  release:
    runs-on: ubuntu-latest
    name: Release Algernon
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # full-clone, needed for commit messages
      - name: Retrieve Release Version
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: hpi-swa/setup-smalltalkCI@v1
        id: smalltalkci
        with:
          smalltalk-image: ${{ ENV.smalltalk }}
      - run: smalltalkci -s ${{ ENV.smalltalk }} ./.release.smalltalk.ston
        shell: bash
        timeout-minutes: 15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate Release Notes
        run: |
          LAST_VERSION=$(git tag --list --sort=-version:refname "v*" | head -2 | tail -1)
          echo "Comparing $LAST_VERSION to $RELEASE_VERSION"
          # Make sure that the latest version number changed
          test "0" -ne "$(git diff --exit-code $LAST_VERSION..$RELEASE_VERSION -- packages/Algernon.package/ALGInstallation.class/instance/latestVersion.st > /dev/null; echo $?)"
          git log $LAST_VERSION..$RELEASE_VERSION --pretty=format:'- %s' | tee ${{ github.workspace }}-CHANGELOG.txt
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ ENV.PATH_TO_SAR }}
          name: Algernon ${{ ENV.RELEASE_VERSION }}
          body_path: ${{ github.workspace }}-CHANGELOG.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

