name: smalltalkCI
on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        smalltalk:
          - Squeak64-5.3
          - Squeak64-trunk
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.smalltalk }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: hpi-swa/setup-smalltalkCI@v1
        id: smalltalkci
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - run: smalltalkci -s ${{ matrix.smalltalk }}
        shell: bash
        timeout-minutes: 15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  baselinetests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        smalltalk:
          - Squeak64-5.3
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.smalltalk }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: hpi-swa/setup-smalltalkCI@v1
        id: smalltalkci
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - run: |
          ALGERNON_GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo "Detected git branch: $ALGERNON_GIT_BRANCH"
          sed -i "s/String empty/$ALGERNON_GIT_BRANCH/g" 'packages/BaselineOfAlgernonTests.package/BOALGTest.class/instance/currentGitBranch.st'
      - run: smalltalkci -s ${{ matrix.smalltalk }} ./.baselinetests.smalltalk.ston
        shell: bash
        timeout-minutes: 15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
